### ISSUE TITLE
Unsupported syntax in n: macros

### ISSUE THREAD

**Issue by mabar** [nette-intellij/intellij-latte#150]
`<a n:href=":App:Admin:User:Edit:default $adminFirewall->getUser()->id">test</a>`
- working in latte
- can click through `$adminFirewall`, but method is not recognized. `$adminFirewall` has error `Multiple definitions for variable 'adminFirewall'` (it is defined just once by {templateType}, `getUser()` has error `Method 'getUser' not found for type 'mixed'`

`<a n:href={:App:Admin:User:Edit:default $adminFirewall->getUser()->id}>test</a>`
- fully understanded by latte plugin
- does not work in latte, throws `Latte\CompileException`

**Comment by mesour** [comment]
Next code working in 1.1.2 without any problems.

```
{templateType LattePlugin\Tests\TestVariables}

<a n:href=":App:Admin:User:Edit:default $userAdmin->getCustomer()->getId()">test</a>
```

```
<?php

namespace LattePlugin\Tests;

use App\Users\UserAdmin;

class TestVariables
{

	/** @var UserAdmin */
	public $userAdmin;

}
```
