### ISSUE TITLE
Allow rewrite variable type using {varType} without causing warnings

### ISSUE THREAD

**Issue by solcik** [nette-intellij/intellij-latte#131]
I have multiple latte files - each has some `define` block.
In this case `$paginator` is highlighted as multiple definitions, but there is only one in this file.

```latte
{define monthPaginator}
    {varType Solcik\Other\Paginator\MonthPaginator $paginator}
    {varType Brick\DateTime\YearMonth $yearMonth}
    <nav>
        <ul class="pagination justify-content-center">
            <li class="page-item" n:foreach="$paginator->getPrevious() as $yearMonth">
                <a class="page-link"
                        n:href="this, year => $yearMonth->getYear(), month => $yearMonth->getMonth()">
                    <span>{$yearMonth}</span>
                </a>
            </li>
            <li class="page-item active">
                <span class="page-link">
                    <span>{$paginator->getCurrent()}</span>
                </span>
            </li>
            <li class="page-item" n:foreach="$paginator->getNext() as $yearMonth">
                <a class="page-link"
                        n:href="this, year => $yearMonth->getYear(), month => $yearMonth->getMonth()">
                    <span>{$yearMonth}</span>
                </a>
            </li>
        </ul>
    </nav>
{/define}
```

<img width="826" alt="Screenshot 2020-11-21 at 11 33 19" src="https://user-images.githubusercontent.com/1543737/99875630-6239cd00-2bf1-11eb-800c-a09b615cc638.png">

**Comment by mesour** [comment]
It is working correctly in 1.1.2
